/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg123015;


import javafx.application.Application;
import javafx.stage.Screen;
import javafx.stage.Stage;
import javafx.scene.*;
import javafx.scene.layout.*;
import javafx.scene.image.Image;

import java.util.Objects;


public class App extends Application {

    Scene scena;

    public static void main(String[] args) {
        //metodo sincrono, aspetto che termini launch prima di eseguire il codice dopo
        launch(args);

    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        MainMenu mm = new MainMenu();
        synchronized (scena = mm.mmScene)
        {
            scena.getStylesheets().add(Objects.requireNonNull(getClass().getResource("/MM_ScenaLvl.css")).toExternalForm());
            primaryStage.setScene(scena);
            primaryStage.setResizable(false);
            primaryStage.getIcons().add(new Image("/icons/AvatarSprite.png"));
            primaryStage.setTitle("Deepest Dungeon - Challengers");
            primaryStage.setY(Screen.getPrimary().getBounds().getHeight()/16);
            primaryStage.setX((Screen.getPrimary().getBounds().getWidth()-800)/2);
            primaryStage.show();
        }


    }

}
