/*
 * This source file was generated by the Gradle 'init' task
 */
package it.unicam.cs.mpgc.rpg123015;


import javafx.application.Application;
import javafx.stage.Stage;
import javafx.scene.*;
import javafx.scene.layout.*;


public class App extends Application {

    Scene scena;

    public static void main(String[] args) {
        //metodo sincrono, aspetto che termini launch prima di eseguire il codice dopo
        launch(args);

    }

    @Override
    public void start(Stage primaryStage) throws Exception {

        MainMenu mm = new MainMenu();
        synchronized (scena = mm.mmScene)
        {
            primaryStage.setScene(scena);
            primaryStage.show();
        }


    }

}
